#!/bin/zsh

export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/Library/Python/3.6/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH=$PATH:/usr/local/sbin
export DISABLE_AUTO_TITLE='true'
export TERM=xterm-256color
export TMUXP_CONFIGDIR=$HOME/.tmuxp
