#!/bin/zsh

export ZSH=$HOME/.oh-my-zsh
export PATH=/Applications/MAMP/bin/php/php7.0.16/bin:$PATH
export PATH=~/Library/Python/3.6/bin:$PATH
export DISABLE_AUTO_TITLE='true'
export TERM=xterm-256color
export TMUXP_CONFIGDIR=$HOME/.tmuxp
